import type { District, ScenarioPreset, Teacher } from "./types";

export const APP_NAME = "EduReg Analytics";
export const APP_TAG = "State & Local Teacher Registry";

export const DISTRICTS: District[] = [
  { id: "d1", name: "Metro Central", zone: "Urban Core", locality: "urban", schools: 42, enrollmentPupils: 38400, teacherTarget: 1097 },
  { id: "d2", name: "North Highlands", zone: "Northern Belt", locality: "rural", schools: 28, enrollmentPupils: 14600, teacherTarget: 486 },
  { id: "d3", name: "Riverine East", zone: "Coastal", locality: "semi-urban", schools: 25, enrollmentPupils: 19800, teacherTarget: 614 },
  { id: "d4", name: "Savannah District", zone: "Central Plains", locality: "rural", schools: 21, enrollmentPupils: 11200, teacherTarget: 398 },
  { id: "d5", name: "Harbour South", zone: "Urban Core", locality: "urban", schools: 36, enrollmentPupils: 32100, teacherTarget: 918 },
  { id: "d6", name: "Hilltop West", zone: "Western Ridge", locality: "semi-urban", schools: 19, enrollmentPupils: 9300, teacherTarget: 332 },
];

export const SUBJECTS = [
  "Mathematics", "English Language", "Physics", "Chemistry", "Biology",
  "Special Education", "Technical & Vocational", "Early Childhood",
  "Computer/ICT", "Civic & Social", "Agricultural Science", "Literature",
];

export const QUALIFICATIONS = ["NCE", "B.Ed", "PGDE", "M.Ed", "PhD"] as const;

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  { id: "baseline", name: "Baseline", desc: "Current policy settings with no intervention.", hardshipAllowance: 5, stemQuota: 18, cpdHours: 20, earlyRetire: 8, ruralIncentive: 1200 },
  { id: "stem-surge", name: "2026 STEM Surge", desc: "Fast-track STEM licensure with higher quotas.", hardshipAllowance: 8, stemQuota: 38, cpdHours: 25, earlyRetire: 6, ruralIncentive: 1800 },
  { id: "hardship-drive", name: "Hardship Retention Drive", desc: "Heavy rural allowance and incentives to close equity gaps.", hardshipAllowance: 18, stemQuota: 22, cpdHours: 30, earlyRetire: 5, ruralIncentive: 3200 },
  { id: "digital-literacy", name: "Universal Digital Literacy", desc: "Mandatory CPD, strong rural reach, modest allowance.", hardshipAllowance: 12, stemQuota: 28, cpdHours: 40, earlyRetire: 7, ruralIncentive: 2200 },
];

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}
function daysAhead(n: number): string {
  return new Date(Date.now() + n * 86400000).toISOString();
}

export const SEED_TEACHERS: Teacher[] = [
  { id: "t01", name: "Aisha Bello", gender: "F", age: 34, yearsExperience: 9, board: "B.Ed", teacherId: "TRCN-2021-0014", district: "Metro Central", school: "Central Model Primary", locality: "urban", subjects: ["Mathematics", "Computer/ICT"], status: "verified", licenseExpiry: daysAhead(300), cpdCredits: 42, verifiedDate: daysAgo(40), lastReview: daysAgo(12), notes: "" },
  { id: "t02", name: "Emeka Okafor", gender: "M", age: 41, yearsExperience: 15, board: "M.Ed", teacherId: "TRCN-2015-0881", district: "North Highlands", school: "Hillview Secondary", locality: "rural", subjects: ["Physics", "Mathematics"], status: "under_review", licenseExpiry: daysAhead(120), cpdCredits: 28, verifiedDate: null, lastReview: daysAgo(3), notes: "Awaiting updated credential scan." },
  { id: "t03", name: "Chioma Nwosu", gender: "F", age: 29, yearsExperience: 5, board: "NCE", teacherId: "LGE-2019-3345", district: "Riverine East", school: "Delta Primary", locality: "semi-urban", subjects: ["Early Childhood", "English Language"], status: "verified", licenseExpiry: daysAhead(210), cpdCredits: 19, verifiedDate: daysAgo(60), lastReview: daysAgo(60), notes: "" },
  { id: "t04", name: "Tunde Adeyemi", gender: "M", age: 52, yearsExperience: 24, board: "PhD", teacherId: "TRCN-2003-1177", district: "Harbour South", school: "Harbour Grammar", locality: "urban", subjects: ["Chemistry", "Biology"], status: "expiring", licenseExpiry: daysAhead(25), cpdCredits: 34, verifiedDate: daysAgo(30), lastReview: daysAgo(2), notes: "License expiring within 90 days, renewal pending." },
  { id: "t05", name: "Fatima Yusuf", gender: "F", age: 38, yearsExperience: 12, board: "B.Ed", teacherId: "TRCN-2014-0922", district: "Savannah District", school: "Grassland Junior", locality: "rural", subjects: ["Biology", "Agricultural Science"], status: "verified", licenseExpiry: daysAhead(400), cpdCredits: 51, verifiedDate: daysAgo(120), lastReview: daysAgo(45), notes: "" },
  { id: "t06", name: "David Mensah", gender: "M", age: 26, yearsExperience: 2, board: "NCE", teacherId: "LGE-2022-4501", district: "Metro Central", school: "Unity Primary", locality: "urban", subjects: ["Mathematics"], status: "provisional", licenseExpiry: daysAhead(150), cpdCredits: 11, verifiedDate: null, lastReview: null, notes: "Provisional license, completing probation." },
  { id: "t07", name: "Grace Adebayo", gender: "F", age: 45, yearsExperience: 19, board: "M.Ed", teacherId: "TRCN-2010-2234", district: "Hilltop West", school: "Ridge Academy", locality: "semi-urban", subjects: ["Special Education", "Civic & Social"], status: "verified", licenseExpiry: daysAhead(270), cpdCredits: 63, verifiedDate: daysAgo(20), lastReview: daysAgo(20), notes: "" },
  { id: "t08", name: "Samuel Ibe", gender: "M", age: 33, yearsExperience: 7, board: "PGDE", teacherId: "TRCN-2018-5603", district: "North Highlands", school: "Summit College", locality: "rural", subjects: ["Computer/ICT", "Mathematics"], status: "under_review", licenseExpiry: daysAhead(180), cpdCredits: 24, verifiedDate: null, lastReview: daysAgo(6), notes: "Subject specialization contested." },
  { id: "t09", name: "Ngozi Eze", gender: "F", age: 31, yearsExperience: 6, board: "B.Ed", teacherId: "TRCN-2017-7812", district: "Harbour South", school: "Marina Girls", locality: "urban", subjects: ["English Language", "Literature"], status: "verified", licenseExpiry: daysAhead(500), cpdCredits: 39, verifiedDate: daysAgo(15), lastReview: daysAgo(15), notes: "" },
  { id: "t10", name: "Yakubu Musa", gender: "M", age: 49, yearsExperience: 21, board: "M.Ed", teacherId: "TRCN-2008-9011", district: "Savannah District", school: "Dune Secondary", locality: "rural", subjects: ["Agricultural Science", "Biology"], status: "transferred", licenseExpiry: daysAhead(90), cpdCredits: 30, verifiedDate: daysAgo(10), lastReview: daysAgo(10), notes: "Transferred from Riverine East." },
  { id: "t11", name: "Blessing Osei", gender: "F", age: 27, yearsExperience: 3, board: "NCE", teacherId: "LGE-2020-6720", district: "Riverine East", school: "Creek Primary", locality: "semi-urban", subjects: ["Early Childhood"], status: "verified", licenseExpiry: daysAhead(320), cpdCredits: 17, verifiedDate: daysAgo(90), lastReview: daysAgo(90), notes: "" },
  { id: "t12", name: "Ibrahim Lawal", gender: "M", age: 36, yearsExperience: 10, board: "B.Ed", teacherId: "TRCN-2016-3456", district: "Hilltop West", school: "Peak Junior", locality: "semi-urban", subjects: ["Physics", "Mathematics"], status: "verified", licenseExpiry: daysAhead(260), cpdCredits: 46, verifiedDate: daysAgo(25), lastReview: daysAgo(25), notes: "" },
  { id: "t13", name: "Linda Uche", gender: "F", age: 42, yearsExperience: 16, board: "M.Ed", teacherId: "TRCN-2011-9080", district: "Metro Central", school: "City International", locality: "urban", subjects: ["Special Education", "English Language"], status: "provisional", licenseExpiry: daysAhead(60), cpdCredits: 22, verifiedDate: null, lastReview: daysAgo(1), notes: "Provisional pending final documents." },
  { id: "t14", name: "Peter Okonkwo", gender: "M", age: 39, yearsExperience: 13, board: "B.Ed", teacherId: "TRCN-2013-1122", district: "North Highlands", school: "Alpine Secondary", locality: "rural", subjects: ["Chemistry"], status: "verified", licenseExpiry: daysAhead(380), cpdCredits: 55, verifiedDate: daysAgo(50), lastReview: daysAgo(50), notes: "" },
  { id: "t15", name: "Amaka Obi", gender: "F", age: 30, yearsExperience: 8, board: "PGDE", teacherId: "TRCN-2018-4550", district: "Harbour South", school: "Quayside Primary", locality: "urban", subjects: ["Mathematics", "Computer/ICT"], status: "verified", licenseExpiry: daysAhead(340), cpdCredits: 37, verifiedDate: daysAgo(5), lastReview: daysAgo(5), notes: "" },
  { id: "t16", name: "Joseph Banda", gender: "M", age: 47, yearsExperience: 20, board: "B.Ed", teacherId: "TRCN-2009-3348", district: "Savannah District", school: "Steppe College", locality: "rural", subjects: ["Biology", "Chemistry"], status: "expiring", licenseExpiry: daysAhead(48), cpdCredits: 26, verifiedDate: daysAgo(18), lastReview: daysAgo(18), notes: "CPD short for renewal." },
  { id: "t17", name: "Hauwa Garba", gender: "F", age: 35, yearsExperience: 11, board: "B.Ed", teacherId: "TRCN-2014-6677", district: "Riverine East", school: "Estuary Secondary", locality: "semi-urban", subjects: ["English Language", "Civic & Social"], status: "verified", licenseExpiry: daysAhead(440), cpdCredits: 44, verifiedDate: daysAgo(70), lastReview: daysAgo(70), notes: "" },
  { id: "t18", name: "Michael John", gender: "M", age: 28, yearsExperience: 4, board: "NCE", teacherId: "LGE-2021-8890", district: "Hilltop West", school: "Cliff Primary", locality: "semi-urban", subjects: ["Mathematics", "Physics"], status: "under_review", licenseExpiry: daysAhead(200), cpdCredits: 14, verifiedDate: null, lastReview: daysAgo(9), notes: "Duplicate registration flagged." },
  { id: "t19", name: "Sandra Okafor", gender: "F", age: 54, yearsExperience: 26, board: "M.Ed", teacherId: "TRCN-2002-5566", district: "Metro Central", school: "Grand Central", locality: "urban", subjects: ["Early Childhood", "Special Education"], status: "expiring", licenseExpiry: daysAhead(30), cpdCredits: 29, verifiedDate: daysAgo(8), lastReview: daysAgo(8), notes: "Retirement eligibility imminent." },
  { id: "t20", name: "Abdul Karim", gender: "M", age: 44, yearsExperience: 17, board: "B.Ed", teacherId: "TRCN-2010-7789", district: "North Highlands", school: "Glacier Secondary", locality: "rural", subjects: ["Computer/ICT", "Technical & Vocational"], status: "verified", licenseExpiry: daysAhead(520), cpdCredits: 58, verifiedDate: daysAgo(100), lastReview: daysAgo(100), notes: "" },
  { id: "t21", name: "Mary Anenu", gender: "F", age: 32, yearsExperience: 6, board: "B.Ed", teacherId: "TRCN-2017-9912", district: "Harbour South", school: "Docklands Primary", locality: "urban", subjects: ["Mathematics"], status: "verified", licenseExpiry: daysAhead(360), cpdCredits: 33, verifiedDate: daysAgo(35), lastReview: daysAgo(35), notes: "" },
  { id: "t22", name: "Chinedu Ubah", gender: "M", age: 37, yearsExperience: 12, board: "PGDE", teacherId: "TRCN-2016-1209", district: "Savannah District", school: "Mesa Primary", locality: "rural", subjects: ["Technical & Vocational", "Computer/ICT"], status: "under_review", licenseExpiry: daysAhead(160), cpdCredits: 21, verifiedDate: null, lastReview: daysAgo(14), notes: "Vocational certification pending." },
  { id: "t23", name: "Rahma Sani", gender: "F", age: 25, yearsExperience: 1, board: "NCE", teacherId: "LGE-2023-5670", district: "Riverine East", school: "Mangrove Primary", locality: "semi-urban", subjects: ["Early Childhood", "English Language"], status: "provisional", licenseExpiry: daysAhead(240), cpdCredits: 6, verifiedDate: null, lastReview: null, notes: "Fresh graduate, provisional." },
  { id: "t24", name: "Victor Eze", gender: "M", age: 30, yearsExperience: 9, board: "B.Ed", teacherId: "TRCN-2019-4421", district: "Hilltop West", school: "Summit Ridge", locality: "semi-urban", subjects: ["Biology", "Chemistry"], status: "verified", licenseExpiry: daysAhead(290), cpdCredits: 41, verifiedDate: daysAgo(28), lastReview: daysAgo(28), notes: "" },
  { id: "t25", name: "Eunice Mohammed", gender: "F", age: 40, yearsExperience: 14, board: "M.Ed", teacherId: "TRCN-2012-8130", district: "Metro Central", school: "Civic Model", locality: "urban", subjects: ["Civic & Social", "Literature"], status: "verified", licenseExpiry: daysAhead(410), cpdCredits: 49, verifiedDate: daysAgo(33), lastReview: daysAgo(33), notes: "" },
  { id: "t26", name: "Ahmed Ibrahim", gender: "M", age: 46, yearsExperience: 18, board: "B.Ed", teacherId: "TRCN-2008-3341", district: "North Highlands", school: "Tundra High", locality: "rural", subjects: ["Agricultural Science"], status: "expiring", licenseExpiry: daysAhead(65), cpdCredits: 18, verifiedDate: daysAgo(16), lastReview: daysAgo(16), notes: "CPD deficit flagged." },
  { id: "t27", name: "Kate Akin", gender: "F", age: 28, yearsExperience: 4, board: "PGDE", teacherId: "TRCN-2020-6789", district: "Harbour South", school: "Anchor Academy", locality: "urban", subjects: ["Early Childhood", "Special Education"], status: "verified", licenseExpiry: daysAhead(310), cpdCredits: 25, verifiedDate: daysAgo(42), lastReview: daysAgo(42), notes: "" },
  { id: "t28", name: "Bashir Dogo", gender: "M", age: 50, yearsExperience: 23, board: "M.Ed", teacherId: "TRCN-2005-2210", district: "Savannah District", school: "Oasis Secondary", locality: "rural", subjects: ["English Language", "Literature"], status: "transferred", licenseExpiry: daysAhead(140), cpdCredits: 36, verifiedDate: daysAgo(7), lastReview: daysAgo(7), notes: "Moved to Metro Central." },
  { id: "t29", name: "Lola Adeleke", gender: "F", age: 33, yearsExperience: 7, board: "B.Ed", teacherId: "TRCN-2018-9990", district: "Riverine East", school: "Bay Primary", locality: "semi-urban", subjects: ["Mathematics", "Computer/ICT"], status: "verified", licenseExpiry: daysAhead(460), cpdCredits: 40, verifiedDate: daysAgo(55), lastReview: daysAgo(55), notes: "" },
  { id: "t30", name: "Christopher Obi", gender: "M", age: 24, yearsExperience: 2, board: "NCE", teacherId: "LGE-2022-1120", district: "Hilltop West", school: "Foothill Primary", locality: "semi-urban", subjects: ["Physics", "Mathematics"], status: "verified", licenseExpiry: daysAhead(330), cpdCredits: 13, verifiedDate: daysAgo(80), lastReview: daysAgo(80), notes: "" },
  { id: "t31", name: "Zainab Ado", gender: "F", age: 43, yearsExperience: 15, board: "B.Ed", teacherId: "TRCN-2011-7634", district: "North Highlands", school: "Frostline Junior", locality: "rural", subjects: ["Chemistry", "Biology"], status: "verified", licenseExpiry: daysAhead(350), cpdCredits: 47, verifiedDate: daysAgo(65), lastReview: daysAgo(65), notes: "" },
  { id: "t32", name: "Frank Okocha", gender: "M", age: 38, yearsExperience: 13, board: "PGDE", teacherId: "TRCN-2015-8812", district: "Harbour South", school: "Lighthouse High", locality: "urban", subjects: ["Technical & Vocational"], status: "expiring", licenseExpiry: daysAhead(45), cpdCredits: 20, verifiedDate: daysAgo(12), lastReview: daysAgo(12), notes: "Vocational licencing renewal due." },
  { id: "t33", name: "Nadia Kayode", gender: "F", age: 36, yearsExperience: 10, board: "M.Ed", teacherId: "TRCN-2017-9076", district: "Metro Central", school: "Nexus Primary", locality: "urban", subjects: ["Special Education", "Early Childhood"], status: "verified", licenseExpiry: daysAhead(390), cpdCredits: 52, verifiedDate: daysAgo(22), lastReview: daysAgo(22), notes: "" },
  { id: "t34", name: "Usman Garba", gender: "M", age: 29, yearsExperience: 5, board: "B.Ed", teacherId: "TRCN-2019-6643", district: "Savannah District", school: "Dustbowl Secondary", locality: "rural", subjects: ["Computer/ICT", "Technical & Vocational"], status: "under_review", licenseExpiry: daysAhead(220), cpdCredits: 23, verifiedDate: null, lastReview: daysAgo(4), notes: "Identity verification in progress." },
  { id: "t35", name: "Chidinma Eze", gender: "F", age: 27, yearsExperience: 3, board: "NCE", teacherId: "LGE-2021-4455", district: "Riverine East", school: "Papyrus Primary", locality: "semi-urban", subjects: ["English Language", "Early Childhood"], status: "verified", licenseExpiry: daysAhead(300), cpdCredits: 16, verifiedDate: daysAgo(75), lastReview: daysAgo(75), notes: "" },
];